version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - '📦 build'

    groups:
      core:
        patterns:
          - "jinja2*"
          - "typing-extensions*"
          - "pyyaml*"
          - "rich-argparse*"

      data:
        patterns:
          - "sqlglot*"
          - "clickhouse-connect*"

      lint:
        patterns:
          - "pre-commit*"
          - "ruff*"
          - "ty"
          - "codespell*"
          - "mdformat*"
          - "black*"
          - "shellcheck*"
          - "actionlint*"
          - "mbake*"
          - "validate-pyproject*"
          - "check-jsonschema*"

      test:
        patterns:
          - "pytest*"

      release:
        patterns:
          - "bumpver*"
          - "build*"
          - "twine*"

      scan:
        patterns:
          - "trivy*"

      default:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - '🤖 ci'
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - '🤖 ci'
    groups:
      github-scripts:
        patterns: [ "*" ]
