version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "python:uv"

    groups:
      prod-core-group:
        patterns:
          - "jinja2*"
          - "typing-extensions*"
          - "pyyaml*"
          - "rich-argparse*"

      prod-data-group:
        patterns:
          - "sqlglot*"
          - "clickhouse-connect*"

      dev-lint-group:
        patterns:
          - "pre-commit*"
          - "ruff*"
          - "ty"
          - "codespell*"
          - "mdformat*"
          - "black*"
          - "shellcheck*"
          - "actionlint*"
          - "mbake*"
          - "validate-pyproject*"
          - "check-jsonschema*"

      dev-test-group:
        patterns:
          - "pytest*"

      dev-release-group:
        patterns:
          - "bumpver*"
          - "build*"
          - "twine*"

      dev-scan-group:
        patterns:
          - "trivy*"

      default-group:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github:
        patterns:
          - "*"
