[project]
name = "gflx-clickhouse-macro"
version = "0.2.4"
description="Clickhouse macros library"
readme = { file = "README.md", content-type = "text/markdown" }
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "GigaFlux team", email = "dev@gigaflux.dev" }]
maintainers = [{ name = "GigaFlux team", email="dev@gigaflux.dev" }]
keywords = [
    "clickhouse",
    "jinja2",
    "sql-generator",
    "templates"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Database",
    "Topic :: Software Development :: Code Generators",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.10,<3.13"
dependencies = [
    "jinja2>=3.1.6",
    "typing-extensions>=4.0.0",
    "pyyaml>=6.0.1",
    "rich-argparse>=1.6.0",
    "sqlglot>=30.12.0",
    "clickhouse-connect>=1.0.0"
]

[dependency-groups]
# Code Linters, Type Checkers, Spell Checkers, Markdown formatters
dev-lint = [
    "pre-commit>=4.5.0",
    "ty>=0.0.11",
    "ruff>=0.15.12",
    "codespell>=2.4.0",
    "mdformat-gfm>=0.1.1",
    "shellcheck-py>=0.10.0",
    "actionlint-py>=1.7.0",
    "mbake>=1.4.5",
    "validate-pyproject[all]>=0.24",
    "check-jsonschema>=0.37.0"
]

# Test group
dev-test = [
    "pytest>=9.0.0",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.0",
    "pytest-html"
]

# Build & Release
dev-release = [
    "bumpver>=2023.1121"
]
# Scan
dev-scan = [
    "trivy-py>=0.70"
]


[tool.uv]
override-dependencies = [
    "cryptography>=50.0.0"
]

[project.urls]
Homepage = "https://github.com/gigaflux/gflx-clickhouse-macro"
Documentation = "https://github.com/gigaflux/gflx-clickhouse-macro#readme"
Repository = "https://github.com/gigaflux/gflx-clickhouse-macro"
Issues = "https://github.com/gigaflux/gflx-clickhouse-macro/issues"
Changelog = "https://github.com/gigaflux/gflx-clickhouse-macro/releases"

[project.scripts]
gflx-macro = "gflx.clickhouse.macro.__main__:main"

[build-system]
requires = ["flit_core >=3.2"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "gflx.clickhouse.macro"

[tool.flit.sdist]
include = ["src/gflx/clickhouse/macro"]

[tool.bumpver]
current_version = "0.2.4"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version} [skip ci]"
commit = true
commit_args = "-s"
tag = false
push = true
pre_commit_hook = "scripts/pre-bump.sh"

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"'
]
"src/gflx/clickhouse/macro/__init__.py" = [
    '__version__ = "{version}"',
]
"src/gflx/clickhouse/macro/dbt_project.yml" = [
    'version: "{version}"'
]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = [
    "-vvv",
    "--cov=gflx.clickhouse.macro",
    "--cov-report=term-missing",
    "--cov-report=xml:.var/coverage.xml",
    "--cov-report=html:.var/htmlcov",
    "--junitxml=.var/junit.xml",
    "--html=.var/report.html",
    "--self-contained-html",
    "--strict-markers"
]
testpaths = ["tests"]
markers = [
    "xdist_group: serial_db"
]
filterwarnings = [
    "ignore::urllib3.exceptions.InsecureRequestWarning",
    "ignore:Failed to generate report:pytest_cov.plugin.CovReportWarning"
]

[tool.coverage.run]
source = ["src"]
omit = [
    "*/__init__.py"
]
disable_warnings = ["no-data-collected", "module-not-imported"]
relative_files = true

[tool.coverage.report]
show_missing = true
skip_empty = true
fail_under = 80
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if __name__ == .__main__.:",
    "raise NotImplementedError",
    "if TYPE_CHECKING:",
    "@(abc\\.)?abstractmethod",
    "\\.\\.\\.",
    "raise AssertionError",
    "except ImportError:",
    "typing\\.cast"
]

[tool.ruff]
src = ["src"]
line-length = 120
exclude = [
    ".git",
    ".idea",
    ".vscode",
    ".venv",
    ".var"
]

[tool.ruff.lint]
extend-select = [
    "F", "E", "W",
    "I", "B", "UP",
    "T20", "PT", "ARG",
    "C4", "RET", "SIM",
    "RUF", "S", "ANN",
    "D", "ERA", "TD", "RUF"]
ignore = ["D107", "D203", "D213"]
task-tags = ["TODO", "FIXME", "XXX", "HACK"]

[tool.ruff.lint.isort]
combine-as-imports = true
default-section = "third-party"
known-first-party = ["gflx"]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
skip-magic-trailing-comma = false
docstring-code-format = true

[tool.ruff.lint.per-file-ignores]
"src/gflx/clickhouse/macro/__init__.py" = [
    "F401",
    "F403",
    "D104"
]
"tests/**/__init__.py" = [
    "D104"
]
"tests/**/*.py" = [
    "S101",
    "S608"
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ty]
rules.all = "error"

[tool.ty.terminal]
output-format = "github"

[tool.codespell]
skip = "./htmlcov,*.js"
check-filenames = true
check-hidden = false
